name: Build KernelSU
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Kernel
      run: |
        chmod +x build.sh
        ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3
        path: AnyKernel3.zip
